name: Compile/Test/Publish

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@gammaswap'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GS_TOKEN}}
      - run: npx hardhat test
      - run: forge test -vvv
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GS_TOKEN}}
