name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GIT_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@gammaswap'
      - run: npm install
      - run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
