name: Node.js Package

on:
  push:
    branches:
      - main
      - package-abi

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@gammaswap'
      - run: npm install
      - run: npx hardhat test
        env:
          NODE_AUTH_TOKEN: ${{secrets.GS_TOKEN}}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GS_TOKEN}}
